### ISSUE TITLE
Minify not completely minifying

### ISSUE THREAD

**Issue by matt-in-a-hat** [mediasuitenz/buildbro#3]
It seems with the minify flag it doesn't uglifyify the modules that browserfiy adds in, so while our code is minified there's a lot in the final bundle that isn't.

**Comment by matt-in-a-hat** [comment]
Using `--minifyglobal` works, however `-mg` doesn't. I assume this is because the flag lib expects 1 character short flags, and treats that the same as `-m -g`. Perhaps the short flag should be just `-g`?

**Comment by markstuart** [comment]
Good spotting @matt-in-a-hat, will update
